### ISSUE TITLE
Launcher->Guest user->Earn page not showing instead it just continues to loading 

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wll-loyalty-launcher#12]
![image](https://github.com/user-attachments/assets/5f225817-4bf3-4f05-82d6-928b27b9c902)

Step 1: clear the database table and option table
Step 2: should not install the launcher add-on
step 3: complete the onboard process and enable the launcher on the add-on page
This issue occurred due to activating the add-on without installing the launcher add-on
If the onboarding issue is fixed, it will be fixed.
https://github.com/wployalty/wll-loyalty-launcher/issues/11

**Comment by sabhari-krr** [comment]
Onboarding issue fixed

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/a94a6df8-4028-4770-81a9-24a89bbdd373)
