### ISSUE TITLE
alert popup->Should change the proper design

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wll-loyalty-launcher#2]
![image](https://github.com/user-attachments/assets/ecc6e44e-35b3-4edc-bf40-0b9f8f03ae27)

**Comment by alagesanbe08** [comment]
Fixed

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/f2c2bf3a-26af-41e5-80c5-97c1b13d1903)
