### ISSUE TITLE
Guest User-> while clicking the error, page was loading 

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wll-loyalty-launcher#6]
[Screencast from 20-12-24 05:46:57 PM IST.webm](https://github.com/user-attachments/assets/a765bb46-db34-4d02-a3d3-d32df407ff44)
![image](https://github.com/user-attachments/assets/b881fcd1-3e09-43dd-9fde-b657682bf453)

**Comment by alagesanbe08** [comment]
Fixed

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/c5a59c37-d53b-4077-ba42-ae1d73efb524)
