### ISSUE TITLE
When I downgrade the version (1.2.0 to 1.2 14) fatal error showing

### ISSUE THREAD

**Issue by Mercypaul27** [wployalty/wll-loyalty-launcher#8]
Step 1: Install the 1.3.0 version
step 2: Install the new launcher plugin also
step 3: set up some campaigns and rewards
step 4:Now install the 1.2 14 version(downgrade), that time the error showing
![image](https://github.com/user-attachments/assets/e740733b-78e4-4097-b702-adb668362918)
![image](https://github.com/user-attachments/assets/a11ca004-197e-4263-a27c-23d5dd90ce6b)

**Comment by alagesanbe08** [comment]
Fixed

**Comment by Mercypaul27** [comment]
Fixed
![image](https://github.com/user-attachments/assets/e696f47f-a79c-47e1-963c-fb471a6a9f47)
